(cl:defpackage pp8-msg
  (:use )
  (:export
   "<DUALSHOCK4BUTTONSTATE>"
   "DUALSHOCK4BUTTONSTATE"
   "<DUALSHOCK4HATSTATE>"
   "DUALSHOCK4HATSTATE"
   "<DUALSHOCK4JOYSTICKSTATE>"
   "DUALSHOCK4JOYSTICKSTATE"
   "<DUALSHOCK4STATE>"
   "DUALSHOCK4STATE"
   "<PP8_STATUS>"
   "PP8_STATUS"
  ))

