(cl:defpackage pp8_msgs-msg
  (:use )
  (:export
   "<DUALSHOCK4BUTTONSTATE>"
   "DUALSHOCK4BUTTONSTATE"
   "<DUALSHOCK4HATSTATE>"
   "DUALSHOCK4HATSTATE"
   "<DUALSHOCK4JOYSTICKSTATE>"
   "DUALSHOCK4JOYSTICKSTATE"
   "<DUALSHOCK4STATE>"
   "DUALSHOCK4STATE"
  ))

